---
# tasks file for garfana
- name: Install required packages
  apt:
    name:
      - gnupg2
      - curl
      - software-properties-common
    state: present
- name: Add the Grafana GPG key and APT repository
  shell: |
    curl https://packages.grafana.com/gpg.key | sudo apt-key add -
    add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  args:
    warn: no   
- name: Install the grafana package
  apt:
    name: grafana
    state: present
    update_cache: yes
  notify:
    - Start grafana
    - Enable grafana

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200

